name: checkout-actions
on: push
jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List file before
        run: ls -a
      - uses: actions/checkout@v4
      - name: List File After
        run: ls -a
        