name: First Workflow
on: [push]
jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World"
            - name: Multiline commands 
              run: |
                python -v
                npm -v
                node -v 