name: Working Dir & Shells
on: [push]
defaults:
  run:
    shell: bash   # change default shell for all job
    # working-directory:     // change default working directory
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_RESPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change working direcotry
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh  #powershell
    steps:
      - name: Display Working Directory & List Files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_RESPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: Python Shell
        shell: python   #python shell
        run: |
          import platform
          print(platform.processor())